# Generated by Django 2.2.28 on 2026-02-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='views',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='page',
            name='views',
            field=models.IntegerField(default=1),
        ),
    ]
